### ISSUE TITLE
Doubt in Virtual Address Translation

### ISSUE THREAD

**Issue by ibrahim5253** [ianw/bottomupcs#38]
> Consider a 64-bit address space divided into (generously large) 64 KiB pages creates `2^64/2^16 = 2^52` pages to be managed; assuming each page requires an 8-byte pointer to a physical location a total of `2^52/2^3 = 2^49` or 512 GiB of contiguous memory is required just for the page table!

If there are `2^52` page table entries and each one holds an 8-byte address, shouldn't the total memory consumed by the page table be `2^52 * 2^3 = 2^55` instead of `2^49`? Sorry, if this sounds dumb, but am I missing something?

**Comment by ianw** [comment]
Thanks for pointing this out
